import s from "./landing.module.css";
export default function Page(){return <div className={s.page}>
<header><div className={`${s.container} ${s.header}`}><a className={s.brand} href="#top">SystemNavigator <span>AI</span></a><nav><a href="#features">サービスの特徴</a><a href="#flow">開発フロー</a><a className={s.pill} href="#contact">お問い合わせ</a></nav></div></header>
<main id="top"><section className={s.hero}><div className={`${s.container} ${s.heroGrid}`}><div><p className={s.label}><i/>クラウドAで稼働中</p><h1>SystemNavigator <em>AI</em></h1><p className={s.lead}>AIと人間のレビューを組み合わせ、ヒアリングから設計、開発、テスト、デプロイ、保守までを支援するサービスです。</p><div className={s.actions}><a className={`${s.button} ${s.primary}`} href="#about">システム開発について</a><a className={`${s.button} ${s.secondary}`} href="#contact">お問い合わせ・AIヒアリング</a></div><div className={s.links}><a href="/docs">APIドキュメント ↗</a><a href="/health">ヘルスチェック ↗</a></div></div><div className={s.visual} aria-hidden="true"><div className={s.ring}/><div className={`${s.ring} ${s.inner}`}/><div className={s.core}><b>AI</b><small>× HUMAN</small></div><span className={`${s.node} ${s.n1}`}>設計</span><span className={`${s.node} ${s.n2}`}>開発</span><span className={`${s.node} ${s.n3}`}>テスト</span><span className={`${s.node} ${s.n4}`}>運用</span></div></div></section>
<section className={s.section} id="about"><div className={s.container}><p className={s.kicker}>ABOUT</p><h2>速さと品質を、どちらも諦めない。</h2><p className={s.intro}>AIの生産性と、専門家による判断・レビューをひとつの開発プロセスに。アイデアを、運用できるシステムへ育てます。</p></div></section>
<section className={`${s.section} ${s.muted}`} id="features"><div className={s.container}><p className={s.kicker}>FEATURES</p><h2>サービスの特徴</h2><div className={s.cards}><article><span>01</span><h3>AIによる開発支援</h3><p>要件整理から実装、検証まで、AIを活用して開発サイクルを加速します。</p></article><article><span>02</span><h3>人間によるレビュー</h3><p>重要な判断には専門家が入り、品質・安全性・ビジネス価値を確認します。</p></article><article><span>03</span><h3>一貫した伴走体制</h3><p>ヒアリングからデプロイ後の保守まで、ひとつの流れとして支援します。</p></article></div></div></section>
<section className={s.section} id="flow"><div className={s.container}><p className={s.kicker}>DEVELOPMENT FLOW</p><h2>開発フロー</h2><ol className={s.flow}><li><span>01</span><b>ヒアリング</b><small>課題と目的を整理</small></li><li><span>02</span><b>設計</b><small>最適な仕組みを提案</small></li><li><span>03</span><b>開発・テスト</b><small>AIと人間で品質を担保</small></li><li><span>04</span><b>デプロイ・保守</b><small>継続的な改善を支援</small></li></ol></div></section>
<section className={s.cta} id="contact"><div className={`${s.container} ${s.ctaIn}`}><div><p className={s.kicker}>GET STARTED</p><h2>まずは、あなたの課題を<br/>聞かせてください。</h2></div><a className={`${s.button} ${s.white}`} href="mailto:contact@example.com">お問い合わせ・AIヒアリング</a></div></section>
</main>
<footer><div className={`${s.container} ${s.foot}`}><b>AIシステム開発プラットフォーム</b><small>© 2026 AI System Development Platform</small></div></footer>
</div>}
