from fastapi import HTTPException


ERROR_STATUS = {
    "INVALID_REQUEST": 400,
    "AUTHENTICATION_REQUIRED": 401,
    "PERMISSION_DENIED": 403,
    "RESOURCE_NOT_FOUND": 404,
    "VERSION_CONFLICT": 409,
    "INVALID_STATE_TRANSITION": 409,
    "FILE_TOO_LARGE": 413,
    "UNSUPPORTED_MEDIA_TYPE": 415,
    "HASH_MISMATCH": 422,
    "AI_RETRY_LIMIT_REACHED": 429,
    "AI_PROVIDER_UNAVAILABLE": 503,
    "INVALID_AMOUNT": 400,
    "INVALID_CONTRACT_STATE": 400,
    "INVALID_ESTIMATE_STATE": 400,
    "PAYMENT_ACTION_FORBIDDEN": 403,
    "PAYMENT_RESOURCE_NOT_FOUND": 404,
    "DUPLICATE_PAYMENT": 409,
    "WEBHOOK_ALREADY_PROCESSED": 409,
    "ESTIMATE_EXPIRED": 422,
    "AMOUNT_MISMATCH": 422,
    "CONTRACT_NOT_ACTIVE": 422,
    "PAYMENT_PROVIDER_UNAVAILABLE": 503,
    "INVALID_TEMPLATE_DATA": 400,
    "INVALID_EMAIL_RECIPIENT": 400,
    "INVALID_CHAT_MESSAGE": 400,
    "CHAT_ACCESS_FORBIDDEN": 403,
    "DOCUMENT_SEND_FORBIDDEN": 403,
    "TEMPLATE_NOT_FOUND": 404,
    "CHAT_ROOM_NOT_FOUND": 404,
    "DUPLICATE_NOTIFICATION": 409,
    "DOCUMENT_ALREADY_GENERATED": 409,
    "INVALID_CHAT_STATE": 409,
    "ATTACHMENT_TOO_LARGE": 413,
    "UNSUPPORTED_ATTACHMENT_TYPE": 415,
    "TEMPLATE_RENDER_FAILED": 422,
    "DOCUMENT_GENERATION_FAILED": 422,
    "EMAIL_PROVIDER_UNAVAILABLE": 503,
}


class AppError(Exception):
    def __init__(self, code: str, message: str):
        self.code = code
        self.message = message
        super().__init__(message)


def http_error(error: AppError) -> HTTPException:
    return HTTPException(
        ERROR_STATUS[error.code], {"code": error.code, "message": error.message}
    )
