"""estimate_contract_payment

Revision ID: 215db73ed802
Revises: 0003_ai_storage_workflow
Create Date: 2026-08-02 15:13:56.138668
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "215db73ed802"
down_revision: str | None = "0003_ai_storage_workflow"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maintenance_plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("monthly_price", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("included_ai_minutes", sa.Integer(), nullable=False),
        sa.Column("included_human_minutes", sa.Integer(), nullable=False),
        sa.Column("backup_retention_days", sa.Integer(), nullable=False),
        sa.Column("support_response_hours", sa.Integer(), nullable=False),
        sa.Column("monitoring_enabled", sa.Boolean(), nullable=False),
        sa.Column("staging_enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_maintenance_plans_org_code",
        "maintenance_plans",
        ["organization_id", "code"],
        unique=True,
        postgresql_where=sa.text("organization_id IS NOT NULL"),
    )
    op.create_index(
        "uq_maintenance_plans_system_code",
        "maintenance_plans",
        ["code"],
        unique=True,
        postgresql_where=sa.text("organization_id IS NULL"),
    )
    op.create_table(
        "payment_customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_customer_id", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "provider", name="uq_payment_customers_org_provider"
        ),
        sa.UniqueConstraint(
            "provider", "provider_customer_id", name="uq_payment_customers_provider_id"
        ),
    )
    op.create_table(
        "payment_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_event_id", name="uq_payment_events_provider_event"
        ),
    )
    op.create_index(
        "ix_payment_events_status_received",
        "payment_events",
        ["status", "received_at"],
        unique=False,
    )
    op.create_table(
        "pricing_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("artifact_type", sa.String(length=50), nullable=False),
        sa.Column("base_price", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column(
            "complexity_multiplier", sa.Numeric(precision=18, scale=8), nullable=False
        ),
        sa.Column(
            "quality_multiplier", sa.Numeric(precision=18, scale=8), nullable=False
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "base_price >= 0 AND complexity_multiplier >= 0 AND quality_multiplier >= 0",
            name="ck_pricing_rules_values",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pricing_rules_resolution",
        "pricing_rules",
        ["organization_id", "artifact_type", "enabled"],
        unique=False,
    )
    op.create_index(
        "uq_pricing_rules_system_type",
        "pricing_rules",
        ["artifact_type"],
        unique=True,
        postgresql_where=sa.text("organization_id IS NULL"),
    )
    op.create_index(
        "uq_pricing_rules_org_type",
        "pricing_rules",
        ["organization_id", "artifact_type"],
        unique=True,
        postgresql_where=sa.text("organization_id IS NOT NULL"),
    )
    op.create_table(
        "estimates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("estimate_number", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft','calculating','internal_review','customer_review','approved','rejected','expired','superseded')",
            name="ck_estimates_status",
        ),
        sa.CheckConstraint(
            "currency = upper(currency) AND length(currency) = 3",
            name="ck_estimates_currency",
        ),
        sa.CheckConstraint(
            "subtotal >= 0 AND tax_amount >= 0 AND total_amount >= 0",
            name="ck_estimates_amounts",
        ),
        sa.CheckConstraint(
            "total_amount = subtotal + tax_amount", name="ck_estimates_total"
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "estimate_number",
            name="uq_estimates_organization_number",
        ),
    )
    op.create_index(
        "ix_estimates_project_status",
        "estimates",
        ["project_id", "status"],
        unique=False,
    )
    op.create_table(
        "payment_methods",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("payment_customer_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_payment_method_id", sa.String(length=255), nullable=False),
        sa.Column("brand", sa.String(length=30), nullable=True),
        sa.Column("last4", sa.String(length=4), nullable=True),
        sa.Column("expiry_month", sa.Integer(), nullable=True),
        sa.Column("expiry_year", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "last4 IS NULL OR last4 ~ '^[0-9]{4}$'", name="ck_payment_methods_last4"
        ),
        sa.CheckConstraint(
            "expiry_month IS NULL OR expiry_month BETWEEN 1 AND 12",
            name="ck_payment_methods_expiry_month",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["payment_customer_id"], ["payment_customers.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider",
            "provider_payment_method_id",
            name="uq_payment_methods_provider_id",
        ),
    )
    op.create_table(
        "estimate_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("estimate_id", sa.UUID(), nullable=False),
        sa.Column("item_type", sa.String(length=30), nullable=False),
        sa.Column("phase", sa.String(length=50), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_reference_id", sa.UUID(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(item_type = 'discount') OR (unit_price >= 0 AND amount >= 0)",
            name="ck_estimate_items_nonnegative",
        ),
        sa.CheckConstraint(
            "item_type IN ('ai_runtime','artifact_value','human_review','cloud','maintenance','option','discount','tax')",
            name="ck_estimate_items_type",
        ),
        sa.CheckConstraint(
            "source_type IN ('ai_run','artifact','manual','pricing_rule','cloud_estimate')",
            name="ck_estimate_items_source",
        ),
        sa.CheckConstraint("quantity >= 0", name="ck_estimate_items_quantity"),
        sa.CheckConstraint(
            "amount = round(quantity * unit_price, 8)",
            name="ck_estimate_items_calculated_amount",
        ),
        sa.ForeignKeyConstraint(["estimate_id"], ["estimates.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "estimate_id", "display_order", name="uq_estimate_items_order"
        ),
    )
    op.create_index(
        "ix_estimate_items_estimate", "estimate_items", ["estimate_id"], unique=False
    )
    op.create_table(
        "artifact_pricing_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("estimate_item_id", sa.UUID(), nullable=False),
        sa.Column("artifact_id", sa.UUID(), nullable=False),
        sa.Column("pricing_rule_id", sa.UUID(), nullable=True),
        sa.Column("artifact_type", sa.String(length=50), nullable=False),
        sa.Column("base_price", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column(
            "complexity_multiplier", sa.Numeric(precision=18, scale=8), nullable=False
        ),
        sa.Column(
            "quality_multiplier", sa.Numeric(precision=18, scale=8), nullable=False
        ),
        sa.Column("screen_count", sa.Integer(), nullable=False),
        sa.Column("api_count", sa.Integer(), nullable=False),
        sa.Column("table_count", sa.Integer(), nullable=False),
        sa.Column("test_case_count", sa.Integer(), nullable=False),
        sa.Column(
            "calculated_value", sa.Numeric(precision=18, scale=8), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "screen_count >= 0 AND api_count >= 0 AND table_count >= 0 AND test_case_count >= 0",
            name="ck_artifact_pricing_counts",
        ),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["estimate_item_id"], ["estimate_items.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["pricing_rule_id"], ["pricing_rules.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("estimate_item_id"),
    )
    op.create_table(
        "contracts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("estimate_id", sa.UUID(), nullable=False),
        sa.Column("contract_number", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("contract_type", sa.String(length=30), nullable=False),
        sa.Column("customer_accepted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("customer_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_accepted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("provider_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terms_version", sa.String(length=50), nullable=False),
        sa.Column("document_artifact_version_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "contract_type IN ('development','maintenance','additional_work')",
            name="ck_contracts_type",
        ),
        sa.CheckConstraint(
            "status IN ('draft','awaiting_customer','awaiting_provider','active','suspended','terminated','completed')",
            name="ck_contracts_status",
        ),
        sa.ForeignKeyConstraint(
            ["customer_accepted_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["document_artifact_version_id"],
            ["artifact_versions.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["estimate_id"], ["estimates.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["provider_accepted_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("estimate_id", name="uq_contracts_estimate"),
        sa.UniqueConstraint(
            "organization_id",
            "contract_number",
            name="uq_contracts_organization_number",
        ),
    )
    op.create_index(
        "ix_contracts_project_status",
        "contracts",
        ["project_id", "status"],
        unique=False,
    )
    op.create_table(
        "maintenance_contracts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("maintenance_plan_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("grace_period_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deletion_scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terminated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','active','past_due','grace_period','suspended','deletion_scheduled','terminated')",
            name="ck_maintenance_contracts_status",
        ),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["maintenance_plan_id"], ["maintenance_plans.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contract_id", name="uq_maintenance_contracts_contract"),
    )
    op.create_index(
        "ix_maintenance_contracts_project_status",
        "maintenance_contracts",
        ["project_id", "status"],
        unique=False,
    )
    op.create_table(
        "payment_intents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_payment_intent_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_message_sanitized", sa.Text(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('requires_payment_method','requires_confirmation','processing','succeeded','failed','cancelled','refunded')",
            name="ck_payment_intents_status",
        ),
        sa.CheckConstraint("amount >= 0", name="ck_payment_intents_amount"),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "provider",
            "idempotency_key",
            name="uq_payment_intents_idempotency",
        ),
        sa.UniqueConstraint(
            "provider",
            "provider_payment_intent_id",
            name="uq_payment_intents_provider_id",
        ),
    )
    op.create_index(
        "ix_payment_intents_contract_status",
        "payment_intents",
        ["contract_id", "status"],
        unique=False,
    )
    op.create_table(
        "maintenance_status_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("maintenance_contract_id", sa.UUID(), nullable=False),
        sa.Column("from_status", sa.String(length=30), nullable=True),
        sa.Column("to_status", sa.String(length=30), nullable=False),
        sa.Column("reason_code", sa.String(length=100), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["maintenance_contract_id"],
            ["maintenance_contracts.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_maintenance_events_contract_effective",
        "maintenance_status_events",
        ["maintenance_contract_id", "effective_at"],
        unique=False,
    )
    op.create_table(
        "resource_deletion_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("maintenance_contract_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("requested_by", sa.UUID(), nullable=True),
        sa.Column("approved_by_first", sa.UUID(), nullable=True),
        sa.Column("approved_by_second", sa.UUID(), nullable=True),
        sa.Column("approved_at_first", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at_second", sa.DateTime(timezone=True), nullable=True),
        sa.Column("execution_reference", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft','pending_first_approval','pending_second_approval','approved','cancelled','executed','failed')",
            name="ck_resource_deletion_requests_status",
        ),
        sa.CheckConstraint(
            "approved_by_first IS NULL OR approved_by_second IS NULL OR approved_by_first <> approved_by_second",
            name="ck_resource_deletion_two_approvers",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_first"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_second"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["maintenance_contract_id"],
            ["maintenance_contracts.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["requested_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_deletion_requests_contract_status",
        "resource_deletion_requests",
        ["maintenance_contract_id", "status"],
        unique=False,
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("maintenance_contract_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_subscription_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["maintenance_contract_id"],
            ["maintenance_contracts.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_subscription_id", name="uq_subscriptions_provider_id"
        ),
    )
    op.create_table(
        "subscription_invoices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("provider_invoice_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("amount_due", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscriptions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_invoice_id"),
    )
    op.execute("""
        CREATE FUNCTION prevent_approved_estimate_mutation() RETURNS trigger AS $$
        BEGIN
            IF (TG_OP = 'UPDATE' AND OLD.status = 'approved') THEN
                RAISE EXCEPTION 'approved estimates are immutable';
            END IF;
            RETURN NEW;
        END; $$ LANGUAGE plpgsql;
        CREATE TRIGGER approved_estimates_immutable BEFORE UPDATE ON estimates FOR EACH ROW EXECUTE FUNCTION prevent_approved_estimate_mutation();
        CREATE FUNCTION prevent_approved_estimate_item_mutation() RETURNS trigger AS $$
        BEGIN
            IF EXISTS (SELECT 1 FROM estimates WHERE id = COALESCE(NEW.estimate_id, OLD.estimate_id) AND status = 'approved') THEN
                RAISE EXCEPTION 'approved estimate items are immutable';
            END IF;
            RETURN COALESCE(NEW, OLD);
        END; $$ LANGUAGE plpgsql;
        CREATE TRIGGER approved_estimate_items_immutable BEFORE INSERT OR UPDATE OR DELETE ON estimate_items FOR EACH ROW EXECUTE FUNCTION prevent_approved_estimate_item_mutation();
        CREATE FUNCTION prevent_billing_event_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'billing events are append-only'; END; $$ LANGUAGE plpgsql;
        CREATE TRIGGER payment_events_append_only BEFORE UPDATE OR DELETE ON payment_events FOR EACH ROW EXECUTE FUNCTION prevent_billing_event_mutation();
        CREATE TRIGGER maintenance_status_events_append_only BEFORE UPDATE OR DELETE ON maintenance_status_events FOR EACH ROW EXECUTE FUNCTION prevent_billing_event_mutation();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DROP TRIGGER IF EXISTS maintenance_status_events_append_only ON maintenance_status_events"
    )
    op.execute("DROP TRIGGER IF EXISTS payment_events_append_only ON payment_events")
    op.execute("DROP FUNCTION IF EXISTS prevent_billing_event_mutation()")
    op.execute(
        "DROP TRIGGER IF EXISTS approved_estimate_items_immutable ON estimate_items"
    )
    op.execute("DROP FUNCTION IF EXISTS prevent_approved_estimate_item_mutation()")
    op.execute("DROP TRIGGER IF EXISTS approved_estimates_immutable ON estimates")
    op.execute("DROP FUNCTION IF EXISTS prevent_approved_estimate_mutation()")
    op.drop_table("subscription_invoices")
    op.drop_table("subscriptions")
    op.drop_index(
        "ix_deletion_requests_contract_status", table_name="resource_deletion_requests"
    )
    op.drop_table("resource_deletion_requests")
    op.drop_index(
        "ix_maintenance_events_contract_effective",
        table_name="maintenance_status_events",
    )
    op.drop_table("maintenance_status_events")
    op.drop_index("ix_payment_intents_contract_status", table_name="payment_intents")
    op.drop_table("payment_intents")
    op.drop_index(
        "ix_maintenance_contracts_project_status", table_name="maintenance_contracts"
    )
    op.drop_table("maintenance_contracts")
    op.drop_index("ix_contracts_project_status", table_name="contracts")
    op.drop_table("contracts")
    op.drop_table("artifact_pricing_snapshots")
    op.drop_index("ix_estimate_items_estimate", table_name="estimate_items")
    op.drop_table("estimate_items")
    op.drop_table("payment_methods")
    op.drop_index("ix_estimates_project_status", table_name="estimates")
    op.drop_table("estimates")
    op.drop_index("ix_pricing_rules_resolution", table_name="pricing_rules")
    op.drop_table("pricing_rules")
    op.drop_index("ix_payment_events_status_received", table_name="payment_events")
    op.drop_table("payment_events")
    op.drop_table("payment_customers")
    op.drop_index(
        "uq_maintenance_plans_system_code",
        table_name="maintenance_plans",
        postgresql_where=sa.text("organization_id IS NULL"),
    )
    op.drop_index(
        "uq_maintenance_plans_org_code",
        table_name="maintenance_plans",
        postgresql_where=sa.text("organization_id IS NOT NULL"),
    )
    op.drop_table("maintenance_plans")
    # ### end Alembic commands ###
