"""project_artifact_review

Revision ID: 57d2abd856ae
Revises: 0002_identity_access
Create Date: 2026-08-02 08:20:51.088271
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '57d2abd856ae'
down_revision: str | None = '0002_identity_access'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_phase', sa.String(length=30), nullable=False),
    sa.Column('customer_user_id', sa.UUID(), nullable=True),
    sa.Column('project_manager_user_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("current_phase IN ('hearing', 'estimate', 'requirements', 'basic_design', 'detailed_design', 'development', 'testing', 'staging', 'acceptance', 'production', 'maintenance')", name='ck_projects_phase'),
    sa.CheckConstraint("status IN ('draft', 'hearing', 'estimating', 'awaiting_payment', 'requirements', 'basic_design', 'detailed_design', 'development', 'testing', 'staging', 'awaiting_acceptance', 'production', 'maintenance', 'suspended', 'closed')", name='ck_projects_status'),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_manager_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'project_code', name='uq_projects_organization_code')
    )
    op.create_index('ix_projects_organization_status', 'projects', ['organization_id', 'status'], unique=False)
    op.create_index('ix_projects_organization_updated', 'projects', ['organization_id', 'updated_at'], unique=False)
    op.create_table('ai_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('request_hash', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message_sanitized', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("operation_type IN ('hearing', 'estimate', 'document_generation', 'code_generation', 'review', 'revision', 'test_generation', 'deployment_analysis')", name='ck_ai_runs_operation'),
    sa.CheckConstraint("provider IN ('openai', 'anthropic')", name='ck_ai_runs_provider'),
    sa.CheckConstraint('estimated_cost IS NULL OR estimated_cost >= 0', name='ck_ai_runs_cost'),
    sa.CheckConstraint('retry_count >= 0', name='ck_ai_runs_retry_count'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_runs_organization_status', 'ai_runs', ['organization_id', 'status'], unique=False)
    op.create_index('ix_ai_runs_project_created', 'ai_runs', ['project_id', 'created_at'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("artifact_type IN ('hearing_sheet', 'estimate', 'requirements_definition', 'basic_design', 'detailed_design', 'screen_design', 'api_specification', 'database_design', 'test_specification', 'test_report', 'operation_manual', 'release_procedure', 'source_code')", name='ck_artifacts_type'),
    sa.CheckConstraint("status IN ('draft', 'ai_reviewing', 'human_reviewing', 'revision_requested', 'approved', 'superseded')", name='ck_artifacts_status'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifacts_organization_type', 'artifacts', ['organization_id', 'artifact_type'], unique=False)
    op.create_index('ix_artifacts_project_status', 'artifacts', ['project_id', 'status'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("project_role IN ('project_owner', 'project_manager', 'reviewer', 'developer', 'customer', 'viewer')", name='ck_project_members_role'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_project_members_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_members_project_user')
    )
    op.create_index('ix_project_members_user_status', 'project_members', ['user_id', 'status'], unique=False)
    op.create_table('artifact_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.String(length=20), nullable=False),
    sa.Column('ai_run_id', sa.UUID(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(generated_by = 'ai' AND ai_run_id IS NOT NULL) OR (generated_by = 'human' AND ai_run_id IS NULL)", name='ck_artifact_versions_ai_run'),
    sa.CheckConstraint("generated_by IN ('human', 'ai')", name='ck_artifact_versions_generated_by'),
    sa.CheckConstraint('file_size >= 0', name='ck_artifact_versions_file_size'),
    sa.CheckConstraint('version_number > 0', name='ck_artifact_versions_number'),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'version_number', name='uq_artifact_versions_number')
    )
    op.create_index('ix_artifact_versions_artifact_created', 'artifact_versions', ['artifact_id', 'created_at'], unique=False)
    op.create_index('ix_artifact_versions_content_hash', 'artifact_versions', ['content_hash'], unique=False)
    op.create_foreign_key('fk_artifacts_current_version', 'artifacts', 'artifact_versions', ['current_version_id'], ['id'], ondelete='RESTRICT')
    op.create_table('approval_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('artifact_version_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('submitted','approved','rejected','changes_requested','resubmitted','customer_accepted')", name='ck_approval_events_action'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_events_project_created', 'approval_events', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_approval_events_version_created', 'approval_events', ['artifact_version_id', 'created_at'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('artifact_version_id', sa.UUID(), nullable=False),
    sa.Column('review_type', sa.String(length=30), nullable=False),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=True),
    sa.Column('ai_run_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(review_type = 'ai' AND ai_run_id IS NOT NULL AND reviewer_user_id IS NULL) OR (review_type <> 'ai' AND reviewer_user_id IS NOT NULL AND ai_run_id IS NULL)", name='ck_reviews_reviewer_source'),
    sa.CheckConstraint("review_type IN ('ai', 'human', 'customer_acceptance', 'security', 'architecture', 'code_quality', 'test_quality')", name='ck_reviews_type'),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'passed', 'failed', 'changes_requested', 'cancelled')", name='ck_reviews_status'),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 100)', name='ck_reviews_score'),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reviews_project_created', 'reviews', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_reviews_version_status', 'reviews', ['artifact_version_id', 'status'], unique=False)
    op.create_table('review_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('comment_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('target_path', sa.String(length=1024), nullable=True),
    sa.Column('target_line', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("severity IN ('info', 'minor', 'major', 'critical')", name='ck_review_comments_severity'),
    sa.CheckConstraint("status IN ('open', 'accepted', 'rejected', 'resolved')", name='ck_review_comments_status'),
    sa.CheckConstraint('length(trim(body)) > 0', name='ck_review_comments_body'),
    sa.CheckConstraint('target_line IS NULL OR target_line > 0', name='ck_review_comments_target_line'),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_comments_review_status', 'review_comments', ['review_id', 'status'], unique=False)
    op.execute("""
        CREATE FUNCTION prevent_artifact_version_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'artifact_versions are immutable'; END; $$ LANGUAGE plpgsql;
        CREATE TRIGGER artifact_versions_immutable BEFORE UPDATE OR DELETE ON artifact_versions FOR EACH ROW EXECUTE FUNCTION prevent_artifact_version_mutation();
        CREATE FUNCTION prevent_approval_event_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'approval_events are append-only'; END; $$ LANGUAGE plpgsql;
        CREATE TRIGGER approval_events_append_only BEFORE UPDATE OR DELETE ON approval_events FOR EACH ROW EXECUTE FUNCTION prevent_approval_event_mutation();
        CREATE FUNCTION prevent_review_history_delete() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'review history cannot be deleted'; END; $$ LANGUAGE plpgsql;
        CREATE TRIGGER reviews_no_delete BEFORE DELETE ON reviews FOR EACH ROW EXECUTE FUNCTION prevent_review_history_delete();
        CREATE TRIGGER review_comments_no_delete BEFORE DELETE ON review_comments FOR EACH ROW EXECUTE FUNCTION prevent_review_history_delete();
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drops only objects created by this revision; never run against RDS without approval.
    op.execute('DROP TRIGGER IF EXISTS review_comments_no_delete ON review_comments')
    op.execute('DROP TRIGGER IF EXISTS reviews_no_delete ON reviews')
    op.execute('DROP FUNCTION IF EXISTS prevent_review_history_delete()')
    op.execute('DROP TRIGGER IF EXISTS approval_events_append_only ON approval_events')
    op.execute('DROP FUNCTION IF EXISTS prevent_approval_event_mutation()')
    op.execute('DROP TRIGGER IF EXISTS artifact_versions_immutable ON artifact_versions')
    op.execute('DROP FUNCTION IF EXISTS prevent_artifact_version_mutation()')
    op.drop_constraint('fk_artifacts_current_version', 'artifacts', type_='foreignkey')
    op.drop_index('ix_review_comments_review_status', table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_index('ix_reviews_version_status', table_name='reviews')
    op.drop_index('ix_reviews_project_created', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_approval_events_version_created', table_name='approval_events')
    op.drop_index('ix_approval_events_project_created', table_name='approval_events')
    op.drop_table('approval_events')
    op.drop_index('ix_artifact_versions_content_hash', table_name='artifact_versions')
    op.drop_index('ix_artifact_versions_artifact_created', table_name='artifact_versions')
    op.drop_table('artifact_versions')
    op.drop_index('ix_project_members_user_status', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index('ix_artifacts_project_status', table_name='artifacts')
    op.drop_index('ix_artifacts_organization_type', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_ai_runs_project_created', table_name='ai_runs')
    op.drop_index('ix_ai_runs_organization_status', table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index('ix_projects_organization_updated', table_name='projects')
    op.drop_index('ix_projects_organization_status', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
