"""notifications_documents_chat

Revision ID: d8685773bc4a
Revises: 215db73ed802
Create Date: 2026-08-02 15:51:38.927731
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "d8685773bc4a"
down_revision: str | None = "215db73ed802"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("template_code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("document_type", sa.String(length=50), nullable=False),
        sa.Column("format", sa.String(length=20), nullable=False),
        sa.Column("locale", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("template_storage_key", sa.String(length=1024), nullable=False),
        sa.Column("schema_version", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "format IN ('html','docx','xlsx','markdown')",
            name="ck_document_templates_format",
        ),
        sa.CheckConstraint(
            "status IN ('draft','approved','retired')",
            name="ck_document_templates_status",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_document_templates_resolution",
        "document_templates",
        ["organization_id", "document_type", "locale", "status", "version_number"],
        unique=False,
    )
    op.create_index(
        "uq_document_templates_org_version",
        "document_templates",
        ["organization_id", "template_code", "locale", "version_number"],
        unique=True,
        postgresql_where=sa.text("organization_id IS NOT NULL"),
    )
    op.create_index(
        "uq_document_templates_system_version",
        "document_templates",
        ["template_code", "locale", "version_number"],
        unique=True,
        postgresql_where=sa.text("organization_id IS NULL"),
    )
    op.create_table(
        "email_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("template_code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("subject_template", sa.String(length=500), nullable=False),
        sa.Column("body_text_template", sa.Text(), nullable=False),
        sa.Column("body_html_template", sa.Text(), nullable=True),
        sa.Column("locale", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft','approved','retired')", name="ck_email_templates_status"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_email_templates_resolution",
        "email_templates",
        ["organization_id", "template_code", "locale", "status", "version_number"],
        unique=False,
    )
    op.create_index(
        "uq_email_templates_org_version",
        "email_templates",
        ["organization_id", "template_code", "locale", "version_number"],
        unique=True,
        postgresql_where=sa.text("organization_id IS NOT NULL"),
    )
    op.create_index(
        "uq_email_templates_system_version",
        "email_templates",
        ["template_code", "locale", "version_number"],
        unique=True,
        postgresql_where=sa.text("organization_id IS NULL"),
    )
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("in_app_enabled", sa.Boolean(), nullable=False),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("digest_mode", sa.String(length=20), nullable=False),
        sa.Column("quiet_hours_start", sa.Time(), nullable=True),
        sa.Column("quiet_hours_end", sa.Time(), nullable=True),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "digest_mode IN ('immediate','hourly','daily','none')",
            name="ck_notification_preferences_digest",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "user_id",
            "event_type",
            name="uq_notification_preferences_scope",
        ),
    )
    op.create_index(
        "ix_notification_preferences_user",
        "notification_preferences",
        ["organization_id", "user_id"],
        unique=False,
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','processing','processed','failed')",
            name="ck_outbox_events_status",
        ),
        sa.CheckConstraint("attempt_count >= 0", name="ck_outbox_events_attempts"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "event_type",
            "aggregate_type",
            "aggregate_id",
            "payload_hash",
            name="uq_outbox_events_deduplication",
        ),
    )
    op.create_index(
        "ix_outbox_events_available",
        "outbox_events",
        ["status", "available_at"],
        unique=False,
    )
    op.create_table(
        "chat_rooms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("room_type", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "room_type IN ('project','support','review','maintenance')",
            name="ck_chat_rooms_type",
        ),
        sa.CheckConstraint(
            "status IN ('active','archived','closed')", name="ck_chat_rooms_status"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chat_rooms_project_status",
        "chat_rooms",
        ["project_id", "status"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("action_url", sa.String(length=1024), nullable=True),
        sa.Column("deduplication_key", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "action_url IS NULL OR (action_url LIKE '/%%' AND action_url NOT LIKE '//%%')",
            name="ck_notifications_internal_url",
        ),
        sa.CheckConstraint(
            "severity IN ('info','success','warning','error','critical')",
            name="ck_notifications_severity",
        ),
        sa.CheckConstraint(
            "status IN ('pending','delivered','read','dismissed','expired')",
            name="ck_notifications_status",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "user_id",
            "deduplication_key",
            name="uq_notifications_deduplication",
        ),
    )
    op.create_index(
        "ix_notifications_user_status_created",
        "notifications",
        ["organization_id", "user_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("chat_room_id", sa.UUID(), nullable=False),
        sa.Column("sender_user_id", sa.UUID(), nullable=True),
        sa.Column("message_type", sa.String(length=30), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reply_to_message_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(message_type IN ('system','ai') AND sender_user_id IS NULL) OR (message_type NOT IN ('system','ai') AND sender_user_id IS NOT NULL)",
            name="ck_chat_messages_sender",
        ),
        sa.CheckConstraint(
            "message_type IN ('user','system','ai','review','change_request')",
            name="ck_chat_messages_type",
        ),
        sa.CheckConstraint(
            "status IN ('active','edited','deleted','moderated')",
            name="ck_chat_messages_status",
        ),
        sa.CheckConstraint(
            "length(trim(body)) BETWEEN 1 AND 10000", name="ck_chat_messages_body"
        ),
        sa.ForeignKeyConstraint(
            ["chat_room_id"], ["chat_rooms.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["reply_to_message_id"], ["chat_messages.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["sender_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chat_messages_room_created",
        "chat_messages",
        ["chat_room_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "email_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("notification_id", sa.UUID(), nullable=True),
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("recipient_user_id", sa.UUID(), nullable=False),
        sa.Column("recipient_email_snapshot", sa.String(length=320), nullable=False),
        sa.Column("subject_snapshot", sa.String(length=500), nullable=False),
        sa.Column("body_text_snapshot", sa.Text(), nullable=False),
        sa.Column("body_html_snapshot", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_message_sanitized", sa.Text(), nullable=True),
        sa.Column("deduplication_key", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft','queued','sending','sent','delivered','failed','cancelled')",
            name="ck_email_messages_status",
        ),
        sa.CheckConstraint("attempt_count >= 0", name="ck_email_messages_attempts"),
        sa.ForeignKeyConstraint(
            ["notification_id"], ["notifications.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["template_id"], ["email_templates.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "deduplication_key",
            name="uq_email_messages_deduplication",
        ),
    )
    op.create_index(
        "ix_email_messages_schedule",
        "email_messages",
        ["status", "scheduled_at"],
        unique=False,
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("notification_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_message_sanitized", sa.Text(), nullable=True),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "channel IN ('in_app','email')", name="ck_notification_deliveries_channel"
        ),
        sa.CheckConstraint(
            "status IN ('pending','scheduled','sending','sent','delivered','failed','cancelled')",
            name="ck_notification_deliveries_status",
        ),
        sa.CheckConstraint(
            "attempt_count >= 0 AND max_attempts BETWEEN 1 AND 10",
            name="ck_notification_deliveries_attempts",
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"], ["notifications.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "notification_id", "channel", name="uq_notification_deliveries_channel"
        ),
    )
    op.create_index(
        "ix_notification_deliveries_schedule",
        "notification_deliveries",
        ["status", "scheduled_at"],
        unique=False,
    )
    op.create_table(
        "change_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("chat_message_id", sa.UUID(), nullable=False),
        sa.Column("requested_by_user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("scope_type", sa.String(length=30), nullable=False),
        sa.Column("estimate_id", sa.UUID(), nullable=True),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('low','normal','high','urgent')",
            name="ck_change_requests_priority",
        ),
        sa.CheckConstraint(
            "scope_type IN ('question','bug','minor_change','major_change','new_feature','infrastructure')",
            name="ck_change_requests_scope",
        ),
        sa.CheckConstraint(
            "status IN ('draft','analyzing','awaiting_customer_approval','approved','rejected','in_progress','completed','cancelled')",
            name="ck_change_requests_status",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["chat_message_id"], ["chat_messages.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["estimate_id"], ["estimates.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_change_requests_project_status",
        "change_requests",
        ["project_id", "status"],
        unique=False,
    )
    op.create_table(
        "chat_attachments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("chat_message_id", sa.UUID(), nullable=False),
        sa.Column("artifact_version_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("file_size >= 0", name="ck_chat_attachments_size"),
        sa.ForeignKeyConstraint(
            ["artifact_version_id"], ["artifact_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["chat_message_id"], ["chat_messages.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "chat_message_id", "artifact_version_id", name="uq_chat_attachments_version"
        ),
    )
    op.create_table(
        "document_generation_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("document_type", sa.String(length=50), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=True),
        sa.Column("artifact_id", sa.UUID(), nullable=True),
        sa.Column("artifact_version_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("output_format", sa.String(length=20), nullable=False),
        sa.Column("input_payload_hash", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_message_sanitized", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "output_format IN ('pdf','docx','xlsx','html','markdown')",
            name="ck_document_jobs_output",
        ),
        sa.CheckConstraint(
            "status IN ('queued','processing','completed','failed','cancelled')",
            name="ck_document_jobs_status",
        ),
        sa.CheckConstraint(
            "attempt_count >= 0 AND max_attempts BETWEEN 1 AND 10",
            name="ck_document_jobs_attempts",
        ),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["artifact_version_id"], ["artifact_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["template_id"], ["document_templates.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "project_id",
            "document_type",
            "template_id",
            "output_format",
            "input_payload_hash",
            name="uq_document_jobs_idempotency",
        ),
    )
    op.create_index(
        "ix_document_jobs_project_status",
        "document_generation_jobs",
        ["project_id", "status"],
        unique=False,
    )
    op.create_table(
        "change_request_impacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("change_request_id", sa.UUID(), nullable=False),
        sa.Column("impact_type", sa.String(length=30), nullable=False),
        sa.Column("target_reference", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "estimated_amount", sa.Numeric(precision=18, scale=8), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "impact_type IN ('screen','api','database','document','test','infrastructure','schedule','cost')",
            name="ck_change_request_impacts_type",
        ),
        sa.CheckConstraint(
            "estimated_minutes >= 0 AND estimated_amount >= 0",
            name="ck_change_request_impacts_values",
        ),
        sa.ForeignKeyConstraint(
            ["change_request_id"], ["change_requests.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_change_request_impacts_request",
        "change_request_impacts",
        ["change_request_id"],
        unique=False,
    )
    op.execute("""
        CREATE FUNCTION prevent_communication_hard_delete() RETURNS trigger AS $$
        BEGIN RAISE EXCEPTION 'communication records require logical deletion'; END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER notifications_no_delete BEFORE DELETE ON notifications FOR EACH ROW EXECUTE FUNCTION prevent_communication_hard_delete();
        CREATE TRIGGER chat_messages_no_delete BEFORE DELETE ON chat_messages FOR EACH ROW EXECUTE FUNCTION prevent_communication_hard_delete();

        CREATE FUNCTION prevent_approved_template_mutation() RETURNS trigger AS $$
        BEGIN
            IF OLD.status = 'approved' THEN RAISE EXCEPTION 'approved templates are immutable'; END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER email_templates_approved_immutable BEFORE UPDATE ON email_templates FOR EACH ROW EXECUTE FUNCTION prevent_approved_template_mutation();
        CREATE TRIGGER document_templates_approved_immutable BEFORE UPDATE ON document_templates FOR EACH ROW EXECUTE FUNCTION prevent_approved_template_mutation();

        CREATE FUNCTION prevent_change_impact_mutation() RETURNS trigger AS $$
        BEGIN RAISE EXCEPTION 'change request impacts are append-only'; END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER change_request_impacts_append_only BEFORE UPDATE OR DELETE ON change_request_impacts FOR EACH ROW EXECUTE FUNCTION prevent_change_impact_mutation();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DROP TRIGGER IF EXISTS change_request_impacts_append_only ON change_request_impacts"
    )
    op.execute("DROP FUNCTION IF EXISTS prevent_change_impact_mutation()")
    op.execute(
        "DROP TRIGGER IF EXISTS document_templates_approved_immutable ON document_templates"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS email_templates_approved_immutable ON email_templates"
    )
    op.execute("DROP FUNCTION IF EXISTS prevent_approved_template_mutation()")
    op.execute("DROP TRIGGER IF EXISTS chat_messages_no_delete ON chat_messages")
    op.execute("DROP TRIGGER IF EXISTS notifications_no_delete ON notifications")
    op.execute("DROP FUNCTION IF EXISTS prevent_communication_hard_delete()")
    op.drop_index(
        "ix_change_request_impacts_request", table_name="change_request_impacts"
    )
    op.drop_table("change_request_impacts")
    op.drop_index(
        "ix_document_jobs_project_status", table_name="document_generation_jobs"
    )
    op.drop_table("document_generation_jobs")
    op.drop_table("chat_attachments")
    op.drop_index("ix_change_requests_project_status", table_name="change_requests")
    op.drop_table("change_requests")
    op.drop_index(
        "ix_notification_deliveries_schedule", table_name="notification_deliveries"
    )
    op.drop_table("notification_deliveries")
    op.drop_index("ix_email_messages_schedule", table_name="email_messages")
    op.drop_table("email_messages")
    op.drop_index("ix_chat_messages_room_created", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index("ix_notifications_user_status_created", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_chat_rooms_project_status", table_name="chat_rooms")
    op.drop_table("chat_rooms")
    op.drop_index("ix_outbox_events_available", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index(
        "ix_notification_preferences_user", table_name="notification_preferences"
    )
    op.drop_table("notification_preferences")
    op.drop_index(
        "uq_email_templates_system_version",
        table_name="email_templates",
        postgresql_where=sa.text("organization_id IS NULL"),
    )
    op.drop_index(
        "uq_email_templates_org_version",
        table_name="email_templates",
        postgresql_where=sa.text("organization_id IS NOT NULL"),
    )
    op.drop_index("ix_email_templates_resolution", table_name="email_templates")
    op.drop_table("email_templates")
    op.drop_index(
        "uq_document_templates_system_version",
        table_name="document_templates",
        postgresql_where=sa.text("organization_id IS NULL"),
    )
    op.drop_index(
        "uq_document_templates_org_version",
        table_name="document_templates",
        postgresql_where=sa.text("organization_id IS NOT NULL"),
    )
    op.drop_index("ix_document_templates_resolution", table_name="document_templates")
    op.drop_table("document_templates")
    # ### end Alembic commands ###
